
# install.packages(c("ncdf4", "lubridate", "tidyverse"))
# install.packages("cowplot")
# install.packages("ggpubr")
# devtools::install_github("cszang/regmap")
# install.packages("GGally")
# install.packages("corrplot")
# install.packages("pcaPP")
library(SPEI)
library(tidyverse)
library(ncdf4)
library(lubridate)
library(regmap)
library(ggpubr)
library(cowplot)
library(GGally)
library(corrplot)
library(gridExtra)
library(pcaPP)